"""Pydantic models for PDF metadata extraction results."""

from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, Field


class EmbeddedMetadata(BaseModel):
    """Metadata extracted directly from PDF document properties."""

    title: str | None = Field(default=None, description="Document title")
    author: str | None = Field(default=None, description="Document author(s)")
    subject: str | None = Field(default=None, description="Document subject")
    creator: str | None = Field(default=None, description="Application that created the PDF")
    producer: str | None = Field(default=None, description="PDF producer software")
    creation_date: datetime | None = Field(default=None, description="When document was created")
    modification_date: datetime | None = Field(default=None, description="When document was last modified")


class AIMetadata(BaseModel):
    """Metadata generated by AI analysis of document content."""

    summary: str = Field(description="2-3 sentence summary of what the document is about")
    keywords: list[str] = Field(
        description="3-7 hashtag-style keywords (e.g., #datascience, #bayesian)",
        min_length=3,
        max_length=7,
    )
    category: str = Field(description="Document category/subject area (e.g., statistics, programming)")
    suggested_filename: str = Field(description="Standardized filename: topic-title-[author]-[year].pdf")


class MetadataResult(BaseModel):
    """Complete metadata extraction result for a single PDF."""

    file_path: Path = Field(description="Path to the processed PDF file")
    file_name: str = Field(description="Original filename")
    page_count: int = Field(description="Total pages in PDF")
    pages_analyzed: int = Field(description="Number of pages analyzed (max 10)")
    embedded: EmbeddedMetadata = Field(description="Embedded PDF metadata")
    ai_generated: AIMetadata | None = Field(
        default=None,
        description="AI-generated metadata (None if AI unavailable)",
    )
    warnings: list[str] = Field(default_factory=list, description="Any warnings during extraction")

    model_config = {
        "json_encoders": {
            Path: str,
            datetime: lambda v: v.isoformat() if v else None,
        }
    }


class BatchResult(BaseModel):
    """Result of batch processing multiple PDFs."""

    directory: Path = Field(description="Processed directory path")
    total_files: int = Field(description="Total PDF files found")
    successful: int = Field(description="Successfully processed")
    failed: int = Field(description="Failed to process")
    results: list[MetadataResult] = Field(description="Individual results")
    errors: list[dict] = Field(default_factory=list, description="Files that failed with error messages")

    model_config = {
        "json_encoders": {
            Path: str,
        }
    }
